//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomNguoiDung
    {
        public NhomNguoiDung()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
    }
}
